config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "user/registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stocks', to: "stocks#search"
  resources :user_stocks, only: [:create, :destroy]
  get "my_friends", to: "users#my_friends"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friends, :class_name => 'User' 
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users,through: :user_stocks

  def self.find_by_ticker?(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

  def self.new_from_lookup(ticker_symbol)
    begin
      looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
      new(name: looked_up_stock.company_name, ticker: looked_up_stock.symbol, last_price: looked_up_stock.close)
    rescue Exception => e
      return nil
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_stocks
  has_many :stock, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  def full_name
    return " #{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymus"
  end

  def stock_already_added?(ticker_symbol)
    stock = Stock.find_by_ticker?(ticker_symbol)
    return false unless stock
    user_stocks.where(stock_id: stock.id).exists?
  end

  def under_stock_limit?
    (user_stocks.count <10)
  end

  def can_add_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_added?(ticker_symbol)
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].blank?
      flash.now[:danger] = "you have entered empty string"
    else
      @stocks = Stock.new_from_lookup(params[:stock])
      flash.now[:danger] = "You have entered an incorrect ticker symbol" unless @stocks
    end

    respond_to do |format|
      format.js { render partial: 'users/result'}
    end
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.find_by_ticker(params[:stock_ticker])
    if stock.blank?
      stock =  Stock.new_from_lookup(params[:stock_ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:success] = "Stock #{@user_stock.stock.ticker} was successfully added to port folio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    @user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    @user_stock.destroy()
    flash[:notice] = "Stock was successfully removed"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @user_stocks = current_user.stock
  end

  def my_friends
    
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController 
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
  <%= link_to "Finance Tracker", root_path, class: "navbar-brand" %>
    <% if current_user%>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav col-md-6">
          <li><%= link_to "My portfolio", my_portfolio_path  %></li>
          <li><%= link_to "My Profile", edit_registration_path(current_user)  %></li>
          <li><%= link_to "Link3", "/path3"  %></li>
        </ul>
        <ul class="navbar navbar-right col-md-4">
          <li class="col-md-8 user-name text-right">
            <i class="fa fa-user"></i>
            <%= current_user.full_name.present? ? current_user.full_name : current_user.email%>
          </li>
          <li class="col-md-4 logout">
            <%= link_to("Logout", destroy_user_session_path, class: "btn btn-xs btn-danger", method: :delete)%>
          </li>
        </ul>
      </div>
      <% end%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FinanceTracker" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render 'layouts/navigation'%>
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/stocks/_list.html.erb
<table class="table table-stripe">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Last Price</th>
      <% if @user.id == current_user.id%>
        <th>Action</th>
      <% end%>
    </tr>
  </thead>
  <tbody>
    <% @user_stocks.each do |user_stock|%>
      <tr>
        <td> <%= user_stock.name %> </td>
        <td> <%= user_stock.ticker %> </td>
        <td> <%= user_stock.last_price %></td>
        <% if @user.id == current_user.id%>
          <td>
            <%= link_to "Delete this stock", user_stock_path(user_stock), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-xs btn-danger'%>
          </td>
        <% end%>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_result.html.erb
<% if params[:action] == 'search'%>
  <div class="results-block">
    <%= bootstrap_flash %>
  </div>
<% end %>

<% if @stocks %>
  <div class="well result-block">
    <strong>Symbol: </strong><%= @stocks.ticker %>
    <strong>Name: </strong><%= @stocks.name %>
    <strong>Last Price: </strong><%= @stocks.last_price%>
    <% if current_user.can_add_stock?(@stocks.ticker) %>
      <%= link_to "Add to my stocks", user_stocks_path(user: current_user, 
                                                stock_ticker: @stocks.ticker),
                                                class: "btn btn-xs btn-success", 
                                                method: :post %>
    <% else %>
      <span class="label label-default">
        stock can not be added because you have already added
        <% if !current_user.under_stock_limit?%>
          10 stocks
        <%end%>
        <% if current_user.stock_already_added?(@stocks.ticker)%>
          this stock
        <%end%>
      </span>
    <% end%>
  </div>
<% end %>

<%= render 'stocks/list'%>

app/views/users/_result.js.erb
$("#results").html("<%= j (render 'users/result.html')%>")

app/views/users/my_friends.html.erb
<h1>My friends </h1>

app/views/users/my_portfolio.html.erb
<h1>My port folio page</h1>
<h3>Search for stock</h3>
<div id="stock-lookup">
  <%= form_tag search_stocks_path, remote: true,  method: :get, id: "stock-lookup-form" do%>
    <div class=" row form-group no-padding text-center col-md-12">
      <div class="col-md-10">
        <%= text_field_tag :stock, params[:stock], placeholder: "stock ticker symbol", autofocus: true, 
        class: "form-control search-box input-lg"
        %>      
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do%>
          <i class="fa fa-search"></i> Look up a stock
        <% end %>
      </div>
    </div>
  <% end%>
</div>
<div id="results">
  <%= render 'users/result' %>%
</div>

app/views/welcome/index.html.erb
<h1 align="center"> Welcome to the finance tracker app </h1>